### ISSUE TITLE
라우터를 적용한다.

### ISSUE THREAD

**Issue by soyoung125** [soyoung125/fin-the-pen-web-v2#12]
### ✨ Describe

react-router-dom을 이용하여 url 주소를 통해 특정 페이지에 접근할 수 있도록 한다.

### ✅ Tasks

- [x] 라우터 적용하기
- [x] 페이지 컨테이너 만들기
  - [x] 로그인 페이지
  - [x] 회원가입 페이지
  - [x] 홈 페이지
  - [x] 마이 페이지
  - [x] 알림 페이지
  - [x] 세팅 페이지
  - [x] 분석 페이지
    - [x] 메인 페이지
    - [x] 상세 페이지
  - [x] 자산관리 페이지
    - [x] 메인 페이지
    - [x] 상세 페이지
      - [x] 저축 목표 금액 설정
        - [x] 메인 페이지
        - [x] 저축 세부 설정 페이지
      - [x] 정기 입출금 금액 설정
        - [x] 메인 페이지
        - [x] 상세 설정 페이지
        - [x] 상세 내역 페이지
      - [x] 카테고리별 자산
      - [x] 일정 관리
- [x] 페이지 주소와 컴포넌트 연결하기
